"""Collect every number the docs site charts from the training artefacts.

Run from Docs-Site/:  python3 scripts/extract_metrics.py
Writes src/data/metrics.json. Each block records the file it came from.
Numbers that exist only in markdown summaries are copied as constants with
their source path next to them.
"""
from __future__ import annotations

import csv
import json
from pathlib import Path

DOCS = Path(__file__).resolve().parents[1]
ROOT = DOCS.parent                      # DepthWizard/
M = ROOT / "Model_Traning"
OUT = DOCS / "src/data/metrics.json"

RUNS = {
    "v2": ROOT.parent / "TEMP/v2/metrics.json",
    "v3": M / "Logs/v3 (2)/metrics.json",
    "v4-kaggle": M / "V4_Kaggle/outputs/v4/metrics.json",
    "v4-2": M / "V4_Kaggle/outputs/v4-2/metrics.json",
    "v4-modal": M / "V4_modal/Output/metrics.json",
    "dav2": M / "DAV2_V1/outputs/dav2-v1/metrics.json",
    "v5-probe": M / "v5/outputs/v5/warm_start/Resume/metrics.json",
}


def rel(p: Path) -> str:
    try:
        return str(p.relative_to(ROOT))
    except ValueError:
        return str(p.relative_to(ROOT.parent))


def r3(x):
    return None if x is None else round(float(x), 3)


def summary(block):
    g = block["global"]
    return {
        "rmse": r3(g["rmse_m"]), "mae": r3(g["mae_m"]), "r": r3(g["pearson_r"]),
        "d1": r3(g["delta1"]), "bias": r3(g.get("bias_m")),
        "bal": r3(block.get("balanced_rmse_m")),
    }


def strata(block):
    return {k: {"rmse": r3(v["rmse_m"]), "bias": r3(v.get("bias_m"))}
            for k, v in block["per_stratum"].items()}


data = {"_note": "Generated by scripts/extract_metrics.py. Do not edit by hand."}
runs = {k: json.loads(p.read_text()) for k, p in RUNS.items() if p.exists()}

# --- per-epoch validation curves ------------------------------------------
# v1 and v2 curves were never written as metrics.json with per-epoch history in
# the v3+ format; copied from Research-Paper/scripts/make_figures.py
# (itself from DOCS/CompetitionContext/Outcome.md).
curves = {
    "v1": [[1, 5.29], [2, 4.14], [3, 4.18], [4, 4.34], [5, 3.61], [6, 3.51],
           [7, 3.39], [8, 3.37], [11, 3.32], [12, 3.34]],
    "v2": [[2, 3.68], [4, 3.68], [6, 3.58], [8, 3.34], [10, 3.39], [12, 3.55],
           [14, 3.21], [16, 3.21], [18, 3.07], [20, 3.18]],
}
for k in ["v3", "v4-kaggle", "v4-2", "v4-modal", "dav2", "v5-probe"]:
    pts = []
    for h in runs[k]["history"]:
        if "val" in h:
            pts.append([h["epoch"], r3(h["val"]["global"]["rmse_m"])])
    curves[k] = pts
data["val_curves"] = {
    "source": ["Research-Paper/scripts/make_figures.py (v1, v2)"]
    + [rel(RUNS[k]) for k in ["v3", "v4-kaggle", "v4-2", "v4-modal", "dav2", "v5-probe"]],
    "series": curves,
}

# --- final validation evals -----------------------------------------------
final = {}
for k in ["v3", "v4-kaggle", "v4-2", "v4-modal", "dav2"]:
    m = runs[k]
    final[k] = {
        "plain": summary(m["final_plain"]),
        "tta": summary(m["final_tta"]),
        "sliding": summary(m["final_sliding_tta"]),
    }
final["v5-probe"] = {"plain": summary(runs["v5-probe"]["final_plain"])}
data["val_final"] = {"source": [rel(RUNS[k]) for k in final], "runs": final}

# --- strata ----------------------------------------------------------------
data["strata"] = {
    "source": [rel(RUNS["v3"]), rel(RUNS["v4-modal"])],
    "order": ["0-2m", "2-5m", "5-10m", "10-20m", "20m+"],
    "rows": {
        "v3 · val (TTA)": strata(runs["v3"]["final_tta"]),
        "v4-modal · val (TTA)": strata(runs["v4-modal"]["final_tta"]),
        "v4-modal · test (TTA)": strata(runs["v4-modal"]["test_gamus_test_tta"]),
    },
}

# --- held-out test ---------------------------------------------------------
t = runs["v4-modal"]
data["test_v4modal"] = {
    "source": [rel(RUNS["v4-modal"]), "Research-Paper/main.tex (Table IV: DFC23, India)"],
    "plain": summary(t["test_gamus_test_plain"]),
    "tta": summary(t["test_gamus_test_tta"]),
    "sliding": summary(t["test_gamus_test_sliding_tta"]),
    "landscape_tta": {k: r3(v["rmse_m"]) for k, v in
                      t["test_gamus_test_tta"].get("per_landscape", {}).items()},
    "dfc23": {"rmse": 4.968, "mae": 1.789, "r": 0.881, "d1": 0.776, "bal": 5.544},
    "india": {"rmse": 2.771, "mae": 0.865, "r": 0.922, "d1": 0.888, "bal": 4.447},
}

# Same-protocol comparison: Model_Traning/v3/outputs/v3_vs_v4_vs_dav2.md
data["same_protocol"] = {
    "source": ["Model_Traning/v3/outputs/v3_vs_v4_vs_dav2.md"],
    "columns": ["v3", "v4-modal", "DAv2"],
    "rows": {
        "GAMUS test · plain": [3.628, 3.373, 3.424],
        "GAMUS test · TTA": [3.565, 3.321, 3.396],
        "GAMUS test · sliding+TTA": [3.822, 3.873, 3.759],
        "India val · plain": [5.456, 2.780, 3.027],
    },
}

# --- v5 runs ---------------------------------------------------------------
data["v5_final"] = {
    "source": ["Model_Traning/V4_modal/FINAL_RUN_RESULTS.md"],
    "epochs": [1, 2, 3, 4, 5, 6, 7],
    "select": [2.717, 2.598, 2.541, 2.512, 2.487, 2.482, 2.481],
    "mvs3dm": [1.602, 1.580, 1.562, 1.554, 1.549, 1.546, 1.545],
    "neon": [3.861, 3.647, 3.549, 3.500, 3.454, 3.447, 3.444],
    "neon_forest": [4.61, 4.35, 4.24, 4.18, 4.12, 4.11, 4.11],
    "gamus_urban": [3.30, 3.30, 3.28, 3.27, 3.27, 3.27, 3.26],
    "us3d": [3.953, 3.899, 3.841, 3.857, 3.871, 3.866, 3.872],
}

# --- MVS3DM LiDAR validation ----------------------------------------------
mv = ROOT / "cartosat_2S_Sample/mvs3dm_results/summary.txt"
sites = []
for line in mv.read_text().splitlines()[1:]:
    parts = line.split()
    if len(parts) == 9 and not line.startswith("pooled"):
        sites.append({"site": parts[0], "px_rmse": float(parts[2]), "bias": float(parts[3]),
                      "r": float(parts[4]), "conf_rmse": float(parts[5]),
                      "cell_rmse": float(parts[6]), "cell_bias": float(parts[7]),
                      "gnd_err": float(parts[8])})
data["mvs3dm"] = {"source": [rel(mv)], "sites": sites,
                  "pooled_px": {"n": 13122448, "rmse": 3.38, "bias": 0.35},
                  "pooled_cell": {"n": 1488, "rmse": 1.35, "bias": 0.36}}

# --- GSD measurements ------------------------------------------------------
gsd_csv = ROOT.parent / "gsd_measurements/summary.csv"
rows = list(csv.DictReader(gsd_csv.open()))
data["gsd"] = {"source": ["gsd_measurements/summary.csv"],
               "rows": [{k: (v if k in ("dataset", "city") else float(v)) for k, v in r.items()}
                        for r in rows]}

OUT.write_text(json.dumps(data, indent=1))
print("wrote", OUT)
